# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'IOSgrpc' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # pod 'XLPagerTabStrip', '~> 8.0'
  pod 'MJRefresh', '~> 3.1'
  pod 'SnapKit', '~> 4.0'
  pod 'MBProgressHUD', '~> 1.1'
  pod 'Kingfisher', '~> 4.6'
  pod 'Firebase/AdMob'
  pod 'Toast-Swift', '~> 3.0'
  # pod 'Google-Mobile-Ads-SDK'
end

target 'xCoinsExt' do
    use_frameworks!
    pod 'SnapKit', '~> 4.0'
end
