// Code generated by protoc-gen-go. DO NOT EDIT.
// source: coin_calc.proto

/*
Package CoinCalc is a generated protocol buffer package.

It is generated from these files:
	coin_calc.proto

It has these top-level messages:
	CoinListRequest
	Coin
	CoinListResponse
	PriceRequest
	CoinPriceResponse
*/
package CoinCalc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CoinListRequest struct {
	Page int32 `protobuf:"varint,1,opt,name=page" json:"page,omitempty"`
}

func (m *CoinListRequest) Reset()                    { *m = CoinListRequest{} }
func (m *CoinListRequest) String() string            { return proto.CompactTextString(m) }
func (*CoinListRequest) ProtoMessage()               {}
func (*CoinListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CoinListRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

type Coin struct {
	Id                   string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Symbol               string `protobuf:"bytes,2,opt,name=symbol" json:"symbol,omitempty"`
	Name                 string `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	PriceUsd             string `protobuf:"bytes,4,opt,name=price_usd,json=priceUsd" json:"price_usd,omitempty"`
	PriceBtc             string `protobuf:"bytes,5,opt,name=price_btc,json=priceBtc" json:"price_btc,omitempty"`
	PercentChangeOneHour string `protobuf:"bytes,6,opt,name=percent_change_one_hour,json=percentChangeOneHour" json:"percent_change_one_hour,omitempty"`
	PercentChangeOneDay  string `protobuf:"bytes,7,opt,name=percent_change_one_day,json=percentChangeOneDay" json:"percent_change_one_day,omitempty"`
	PercentChangeOneWeek string `protobuf:"bytes,8,opt,name=percent_change_one_week,json=percentChangeOneWeek" json:"percent_change_one_week,omitempty"`
	MarketCapUsd         string `protobuf:"bytes,9,opt,name=market_cap_usd,json=marketCapUsd" json:"market_cap_usd,omitempty"`
	OneDayVolumnUsd      string `protobuf:"bytes,10,opt,name=one_day_volumn_usd,json=oneDayVolumnUsd" json:"one_day_volumn_usd,omitempty"`
	AvailableSupply      string `protobuf:"bytes,11,opt,name=available_supply,json=availableSupply" json:"available_supply,omitempty"`
	TotalSupply          string `protobuf:"bytes,12,opt,name=total_supply,json=totalSupply" json:"total_supply,omitempty"`
}

func (m *Coin) Reset()                    { *m = Coin{} }
func (m *Coin) String() string            { return proto.CompactTextString(m) }
func (*Coin) ProtoMessage()               {}
func (*Coin) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Coin) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Coin) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *Coin) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Coin) GetPriceUsd() string {
	if m != nil {
		return m.PriceUsd
	}
	return ""
}

func (m *Coin) GetPriceBtc() string {
	if m != nil {
		return m.PriceBtc
	}
	return ""
}

func (m *Coin) GetPercentChangeOneHour() string {
	if m != nil {
		return m.PercentChangeOneHour
	}
	return ""
}

func (m *Coin) GetPercentChangeOneDay() string {
	if m != nil {
		return m.PercentChangeOneDay
	}
	return ""
}

func (m *Coin) GetPercentChangeOneWeek() string {
	if m != nil {
		return m.PercentChangeOneWeek
	}
	return ""
}

func (m *Coin) GetMarketCapUsd() string {
	if m != nil {
		return m.MarketCapUsd
	}
	return ""
}

func (m *Coin) GetOneDayVolumnUsd() string {
	if m != nil {
		return m.OneDayVolumnUsd
	}
	return ""
}

func (m *Coin) GetAvailableSupply() string {
	if m != nil {
		return m.AvailableSupply
	}
	return ""
}

func (m *Coin) GetTotalSupply() string {
	if m != nil {
		return m.TotalSupply
	}
	return ""
}

type CoinListResponse struct {
	Coins []*Coin `protobuf:"bytes,1,rep,name=coins" json:"coins,omitempty"`
}

func (m *CoinListResponse) Reset()                    { *m = CoinListResponse{} }
func (m *CoinListResponse) String() string            { return proto.CompactTextString(m) }
func (*CoinListResponse) ProtoMessage()               {}
func (*CoinListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CoinListResponse) GetCoins() []*Coin {
	if m != nil {
		return m.Coins
	}
	return nil
}

type PriceRequest struct {
	Coinids []string `protobuf:"bytes,1,rep,name=coinids" json:"coinids,omitempty"`
}

func (m *PriceRequest) Reset()                    { *m = PriceRequest{} }
func (m *PriceRequest) String() string            { return proto.CompactTextString(m) }
func (*PriceRequest) ProtoMessage()               {}
func (*PriceRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *PriceRequest) GetCoinids() []string {
	if m != nil {
		return m.Coinids
	}
	return nil
}

type CoinPriceResponse struct {
	Coins []*Coin `protobuf:"bytes,1,rep,name=coins" json:"coins,omitempty"`
}

func (m *CoinPriceResponse) Reset()                    { *m = CoinPriceResponse{} }
func (m *CoinPriceResponse) String() string            { return proto.CompactTextString(m) }
func (*CoinPriceResponse) ProtoMessage()               {}
func (*CoinPriceResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *CoinPriceResponse) GetCoins() []*Coin {
	if m != nil {
		return m.Coins
	}
	return nil
}

func init() {
	proto.RegisterType((*CoinListRequest)(nil), "CoinCalc.CoinListRequest")
	proto.RegisterType((*Coin)(nil), "CoinCalc.Coin")
	proto.RegisterType((*CoinListResponse)(nil), "CoinCalc.CoinListResponse")
	proto.RegisterType((*PriceRequest)(nil), "CoinCalc.PriceRequest")
	proto.RegisterType((*CoinPriceResponse)(nil), "CoinCalc.CoinPriceResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for CoinCalc service

type CoinCalcClient interface {
	GetCoins(ctx context.Context, in *CoinListRequest, opts ...grpc.CallOption) (*CoinListResponse, error)
	GetCoinPrices(ctx context.Context, in *PriceRequest, opts ...grpc.CallOption) (*CoinPriceResponse, error)
}

type coinCalcClient struct {
	cc *grpc.ClientConn
}

func NewCoinCalcClient(cc *grpc.ClientConn) CoinCalcClient {
	return &coinCalcClient{cc}
}

func (c *coinCalcClient) GetCoins(ctx context.Context, in *CoinListRequest, opts ...grpc.CallOption) (*CoinListResponse, error) {
	out := new(CoinListResponse)
	err := grpc.Invoke(ctx, "/CoinCalc.CoinCalc/GetCoins", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coinCalcClient) GetCoinPrices(ctx context.Context, in *PriceRequest, opts ...grpc.CallOption) (*CoinPriceResponse, error) {
	out := new(CoinPriceResponse)
	err := grpc.Invoke(ctx, "/CoinCalc.CoinCalc/GetCoinPrices", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for CoinCalc service

type CoinCalcServer interface {
	GetCoins(context.Context, *CoinListRequest) (*CoinListResponse, error)
	GetCoinPrices(context.Context, *PriceRequest) (*CoinPriceResponse, error)
}

func RegisterCoinCalcServer(s *grpc.Server, srv CoinCalcServer) {
	s.RegisterService(&_CoinCalc_serviceDesc, srv)
}

func _CoinCalc_GetCoins_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CoinListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoinCalcServer).GetCoins(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CoinCalc.CoinCalc/GetCoins",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoinCalcServer).GetCoins(ctx, req.(*CoinListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoinCalc_GetCoinPrices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PriceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoinCalcServer).GetCoinPrices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CoinCalc.CoinCalc/GetCoinPrices",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoinCalcServer).GetCoinPrices(ctx, req.(*PriceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CoinCalc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "CoinCalc.CoinCalc",
	HandlerType: (*CoinCalcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCoins",
			Handler:    _CoinCalc_GetCoins_Handler,
		},
		{
			MethodName: "GetCoinPrices",
			Handler:    _CoinCalc_GetCoinPrices_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "coin_calc.proto",
}

func init() { proto.RegisterFile("coin_calc.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 433 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0xcd, 0x6e, 0x13, 0x31,
	0x10, 0xc7, 0x95, 0xcf, 0x26, 0x93, 0x90, 0x14, 0x83, 0x82, 0x49, 0x2f, 0x65, 0x55, 0xa4, 0x20,
	0xa4, 0x1e, 0x5a, 0x21, 0xc1, 0x11, 0x52, 0x09, 0x0e, 0x48, 0xa0, 0x45, 0xc0, 0x71, 0xe5, 0x78,
	0x47, 0xad, 0x15, 0xc7, 0x36, 0x6b, 0x6f, 0x51, 0x9e, 0x83, 0x17, 0xe2, 0xd1, 0x90, 0x67, 0x37,
	0x5f, 0x28, 0x1c, 0xb8, 0x8d, 0xff, 0xff, 0xdf, 0x7c, 0x69, 0x67, 0x61, 0x2c, 0xad, 0x32, 0x99,
	0x14, 0x5a, 0x5e, 0xba, 0xc2, 0x06, 0xcb, 0x7a, 0x73, 0xab, 0xcc, 0x5c, 0x68, 0x99, 0x3c, 0x87,
	0x71, 0x8c, 0x3f, 0x2a, 0x1f, 0x52, 0xfc, 0x51, 0xa2, 0x0f, 0x8c, 0x41, 0xdb, 0x89, 0x5b, 0xe4,
	0x8d, 0xf3, 0xc6, 0xac, 0x93, 0x52, 0x9c, 0xfc, 0x6e, 0x41, 0x3b, 0x72, 0x6c, 0x04, 0x4d, 0x95,
	0x93, 0xd5, 0x4f, 0x9b, 0x2a, 0x67, 0x13, 0xe8, 0xfa, 0xf5, 0x6a, 0x61, 0x35, 0x6f, 0x92, 0x56,
	0xbf, 0x62, 0x11, 0x23, 0x56, 0xc8, 0x5b, 0xa4, 0x52, 0xcc, 0xce, 0xa0, 0xef, 0x0a, 0x25, 0x31,
	0x2b, 0x7d, 0xce, 0xdb, 0x64, 0xf4, 0x48, 0xf8, 0xea, 0xf3, 0x9d, 0xb9, 0x08, 0x92, 0x77, 0xf6,
	0xcc, 0x77, 0x41, 0xb2, 0x57, 0xf0, 0xc4, 0x61, 0x21, 0xd1, 0x84, 0x4c, 0xde, 0x09, 0x73, 0x8b,
	0x99, 0x35, 0x98, 0xdd, 0xd9, 0xb2, 0xe0, 0x5d, 0x42, 0x1f, 0xd7, 0xf6, 0x9c, 0xdc, 0x4f, 0x06,
	0x3f, 0xd8, 0xb2, 0x60, 0xd7, 0x30, 0x39, 0x92, 0x96, 0x8b, 0x35, 0x3f, 0xa1, 0xac, 0x47, 0x7f,
	0x67, 0xdd, 0x88, 0xf5, 0x3f, 0x7a, 0xfd, 0x44, 0x5c, 0xf2, 0xde, 0xf1, 0x5e, 0xdf, 0x11, 0x97,
	0xec, 0x02, 0x46, 0x2b, 0x51, 0x2c, 0x31, 0x64, 0x52, 0x38, 0xda, 0xb0, 0x4f, 0xf4, 0xb0, 0x52,
	0xe7, 0xc2, 0xc5, 0x2d, 0x5f, 0x02, 0xab, 0x47, 0xc8, 0xee, 0xad, 0x2e, 0x57, 0x86, 0x48, 0x20,
	0x72, 0x6c, 0x69, 0x80, 0x6f, 0xa4, 0x47, 0xf8, 0x05, 0x9c, 0x8a, 0x7b, 0xa1, 0xb4, 0x58, 0x68,
	0xcc, 0x7c, 0xe9, 0x9c, 0x5e, 0xf3, 0x41, 0x85, 0x6e, 0xf5, 0x2f, 0x24, 0xb3, 0x67, 0x30, 0x0c,
	0x36, 0x08, 0xbd, 0xc1, 0x86, 0x84, 0x0d, 0x48, 0xab, 0x90, 0xe4, 0x35, 0x9c, 0xee, 0xbe, 0xb4,
	0x77, 0xd6, 0x78, 0x64, 0x17, 0xd0, 0x89, 0xa7, 0xe1, 0x79, 0xe3, 0xbc, 0x35, 0x1b, 0x5c, 0x8d,
	0x2e, 0x37, 0x77, 0x41, 0x41, 0x5a, 0x99, 0xc9, 0x0c, 0x86, 0x9f, 0xe3, 0x97, 0xd8, 0x1c, 0x08,
	0x87, 0x93, 0x68, 0xa8, 0xbc, 0xca, 0xeb, 0xa7, 0x9b, 0x67, 0xf2, 0x06, 0x1e, 0xc6, 0xc4, 0x9a,
	0xfe, 0x9f, 0x26, 0x57, 0xbf, 0x1a, 0xb0, 0xbd, 0x4a, 0xf6, 0x16, 0x7a, 0xef, 0x31, 0xc4, 0xa7,
	0x67, 0x4f, 0x0f, 0xf9, 0xbd, 0x4b, 0x9d, 0x4e, 0x8f, 0x59, 0x75, 0xd7, 0x1b, 0x78, 0x50, 0x97,
	0xa0, 0x69, 0x3c, 0x9b, 0xec, 0xe0, 0xfd, 0x6d, 0xa6, 0x67, 0x87, 0x45, 0x0e, 0x66, 0x5f, 0x74,
	0xe9, 0x7f, 0xb9, 0xfe, 0x13, 0x00, 0x00, 0xff, 0xff, 0xa4, 0xeb, 0x77, 0x01, 0x42, 0x03, 0x00,
	0x00,
}
