// Code generated by protoc-gen-go. DO NOT EDIT.
// source: coin_calc.proto

/*
Package CoinCalc is a generated protocol buffer package.

It is generated from these files:
	coin_calc.proto

It has these top-level messages:
	CoinListRequest
	Coin
	UserCoin
	CoinListResponse
	PriceRequest
	CoinPriceResponse
	SetUserCoinRequest
	SetUserCoinResponse
	GetUserCoinRequest
	GetUserCoinsResponse
	DeleteUserCoinRequest
	Empty
*/
package CoinCalc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CoinListRequest struct {
	Page int32 `protobuf:"varint,1,opt,name=page" json:"page,omitempty"`
}

func (m *CoinListRequest) Reset()                    { *m = CoinListRequest{} }
func (m *CoinListRequest) String() string            { return proto.CompactTextString(m) }
func (*CoinListRequest) ProtoMessage()               {}
func (*CoinListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CoinListRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

type Coin struct {
	Id                   string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Symbol               string `protobuf:"bytes,2,opt,name=symbol" json:"symbol,omitempty"`
	Name                 string `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	PriceUsd             string `protobuf:"bytes,4,opt,name=price_usd,json=priceUsd" json:"price_usd,omitempty"`
	PriceBtc             string `protobuf:"bytes,5,opt,name=price_btc,json=priceBtc" json:"price_btc,omitempty"`
	PercentChangeOneHour string `protobuf:"bytes,6,opt,name=percent_change_one_hour,json=percentChangeOneHour" json:"percent_change_one_hour,omitempty"`
	PercentChangeOneDay  string `protobuf:"bytes,7,opt,name=percent_change_one_day,json=percentChangeOneDay" json:"percent_change_one_day,omitempty"`
	PercentChangeOneWeek string `protobuf:"bytes,8,opt,name=percent_change_one_week,json=percentChangeOneWeek" json:"percent_change_one_week,omitempty"`
	MarketCapUsd         string `protobuf:"bytes,9,opt,name=market_cap_usd,json=marketCapUsd" json:"market_cap_usd,omitempty"`
	OneDayVolumnUsd      string `protobuf:"bytes,10,opt,name=one_day_volumn_usd,json=oneDayVolumnUsd" json:"one_day_volumn_usd,omitempty"`
	AvailableSupply      string `protobuf:"bytes,11,opt,name=available_supply,json=availableSupply" json:"available_supply,omitempty"`
	TotalSupply          string `protobuf:"bytes,12,opt,name=total_supply,json=totalSupply" json:"total_supply,omitempty"`
}

func (m *Coin) Reset()                    { *m = Coin{} }
func (m *Coin) String() string            { return proto.CompactTextString(m) }
func (*Coin) ProtoMessage()               {}
func (*Coin) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Coin) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Coin) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *Coin) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Coin) GetPriceUsd() string {
	if m != nil {
		return m.PriceUsd
	}
	return ""
}

func (m *Coin) GetPriceBtc() string {
	if m != nil {
		return m.PriceBtc
	}
	return ""
}

func (m *Coin) GetPercentChangeOneHour() string {
	if m != nil {
		return m.PercentChangeOneHour
	}
	return ""
}

func (m *Coin) GetPercentChangeOneDay() string {
	if m != nil {
		return m.PercentChangeOneDay
	}
	return ""
}

func (m *Coin) GetPercentChangeOneWeek() string {
	if m != nil {
		return m.PercentChangeOneWeek
	}
	return ""
}

func (m *Coin) GetMarketCapUsd() string {
	if m != nil {
		return m.MarketCapUsd
	}
	return ""
}

func (m *Coin) GetOneDayVolumnUsd() string {
	if m != nil {
		return m.OneDayVolumnUsd
	}
	return ""
}

func (m *Coin) GetAvailableSupply() string {
	if m != nil {
		return m.AvailableSupply
	}
	return ""
}

func (m *Coin) GetTotalSupply() string {
	if m != nil {
		return m.TotalSupply
	}
	return ""
}

type UserCoin struct {
	User   string `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
	Symbol string `protobuf:"bytes,2,opt,name=symbol" json:"symbol,omitempty"`
	Name   string `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Cnt    string `protobuf:"bytes,4,opt,name=cnt" json:"cnt,omitempty"`
	Coin   *Coin  `protobuf:"bytes,5,opt,name=coin" json:"coin,omitempty"`
}

func (m *UserCoin) Reset()                    { *m = UserCoin{} }
func (m *UserCoin) String() string            { return proto.CompactTextString(m) }
func (*UserCoin) ProtoMessage()               {}
func (*UserCoin) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *UserCoin) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *UserCoin) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *UserCoin) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserCoin) GetCnt() string {
	if m != nil {
		return m.Cnt
	}
	return ""
}

func (m *UserCoin) GetCoin() *Coin {
	if m != nil {
		return m.Coin
	}
	return nil
}

type CoinListResponse struct {
	Coins []*Coin `protobuf:"bytes,1,rep,name=coins" json:"coins,omitempty"`
}

func (m *CoinListResponse) Reset()                    { *m = CoinListResponse{} }
func (m *CoinListResponse) String() string            { return proto.CompactTextString(m) }
func (*CoinListResponse) ProtoMessage()               {}
func (*CoinListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *CoinListResponse) GetCoins() []*Coin {
	if m != nil {
		return m.Coins
	}
	return nil
}

type PriceRequest struct {
	Symbols []string `protobuf:"bytes,1,rep,name=symbols" json:"symbols,omitempty"`
}

func (m *PriceRequest) Reset()                    { *m = PriceRequest{} }
func (m *PriceRequest) String() string            { return proto.CompactTextString(m) }
func (*PriceRequest) ProtoMessage()               {}
func (*PriceRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *PriceRequest) GetSymbols() []string {
	if m != nil {
		return m.Symbols
	}
	return nil
}

type CoinPriceResponse struct {
	Coins []*Coin `protobuf:"bytes,1,rep,name=coins" json:"coins,omitempty"`
}

func (m *CoinPriceResponse) Reset()                    { *m = CoinPriceResponse{} }
func (m *CoinPriceResponse) String() string            { return proto.CompactTextString(m) }
func (*CoinPriceResponse) ProtoMessage()               {}
func (*CoinPriceResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *CoinPriceResponse) GetCoins() []*Coin {
	if m != nil {
		return m.Coins
	}
	return nil
}

type SetUserCoinRequest struct {
	Uc *UserCoin `protobuf:"bytes,1,opt,name=uc" json:"uc,omitempty"`
}

func (m *SetUserCoinRequest) Reset()                    { *m = SetUserCoinRequest{} }
func (m *SetUserCoinRequest) String() string            { return proto.CompactTextString(m) }
func (*SetUserCoinRequest) ProtoMessage()               {}
func (*SetUserCoinRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *SetUserCoinRequest) GetUc() *UserCoin {
	if m != nil {
		return m.Uc
	}
	return nil
}

type SetUserCoinResponse struct {
	Uc *UserCoin `protobuf:"bytes,1,opt,name=uc" json:"uc,omitempty"`
}

func (m *SetUserCoinResponse) Reset()                    { *m = SetUserCoinResponse{} }
func (m *SetUserCoinResponse) String() string            { return proto.CompactTextString(m) }
func (*SetUserCoinResponse) ProtoMessage()               {}
func (*SetUserCoinResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *SetUserCoinResponse) GetUc() *UserCoin {
	if m != nil {
		return m.Uc
	}
	return nil
}

type GetUserCoinRequest struct {
	User string `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
}

func (m *GetUserCoinRequest) Reset()                    { *m = GetUserCoinRequest{} }
func (m *GetUserCoinRequest) String() string            { return proto.CompactTextString(m) }
func (*GetUserCoinRequest) ProtoMessage()               {}
func (*GetUserCoinRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *GetUserCoinRequest) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

type GetUserCoinsResponse struct {
	Ucs []*UserCoin `protobuf:"bytes,1,rep,name=ucs" json:"ucs,omitempty"`
}

func (m *GetUserCoinsResponse) Reset()                    { *m = GetUserCoinsResponse{} }
func (m *GetUserCoinsResponse) String() string            { return proto.CompactTextString(m) }
func (*GetUserCoinsResponse) ProtoMessage()               {}
func (*GetUserCoinsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *GetUserCoinsResponse) GetUcs() []*UserCoin {
	if m != nil {
		return m.Ucs
	}
	return nil
}

type DeleteUserCoinRequest struct {
	User   string `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
	Symbol string `protobuf:"bytes,2,opt,name=symbol" json:"symbol,omitempty"`
	Name   string `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
}

func (m *DeleteUserCoinRequest) Reset()                    { *m = DeleteUserCoinRequest{} }
func (m *DeleteUserCoinRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteUserCoinRequest) ProtoMessage()               {}
func (*DeleteUserCoinRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *DeleteUserCoinRequest) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *DeleteUserCoinRequest) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *DeleteUserCoinRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func init() {
	proto.RegisterType((*CoinListRequest)(nil), "CoinCalc.CoinListRequest")
	proto.RegisterType((*Coin)(nil), "CoinCalc.Coin")
	proto.RegisterType((*UserCoin)(nil), "CoinCalc.UserCoin")
	proto.RegisterType((*CoinListResponse)(nil), "CoinCalc.CoinListResponse")
	proto.RegisterType((*PriceRequest)(nil), "CoinCalc.PriceRequest")
	proto.RegisterType((*CoinPriceResponse)(nil), "CoinCalc.CoinPriceResponse")
	proto.RegisterType((*SetUserCoinRequest)(nil), "CoinCalc.SetUserCoinRequest")
	proto.RegisterType((*SetUserCoinResponse)(nil), "CoinCalc.SetUserCoinResponse")
	proto.RegisterType((*GetUserCoinRequest)(nil), "CoinCalc.GetUserCoinRequest")
	proto.RegisterType((*GetUserCoinsResponse)(nil), "CoinCalc.GetUserCoinsResponse")
	proto.RegisterType((*DeleteUserCoinRequest)(nil), "CoinCalc.DeleteUserCoinRequest")
	proto.RegisterType((*Empty)(nil), "CoinCalc.Empty")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for CoinCalc service

type CoinCalcClient interface {
	GetCoins(ctx context.Context, in *CoinListRequest, opts ...grpc.CallOption) (*CoinListResponse, error)
	GetCoinPrices(ctx context.Context, in *PriceRequest, opts ...grpc.CallOption) (*CoinPriceResponse, error)
	SetUserCoin(ctx context.Context, in *SetUserCoinRequest, opts ...grpc.CallOption) (*SetUserCoinResponse, error)
	GetUserCoins(ctx context.Context, in *GetUserCoinRequest, opts ...grpc.CallOption) (*GetUserCoinsResponse, error)
	DeleteUserCoin(ctx context.Context, in *DeleteUserCoinRequest, opts ...grpc.CallOption) (*Empty, error)
}

type coinCalcClient struct {
	cc *grpc.ClientConn
}

func NewCoinCalcClient(cc *grpc.ClientConn) CoinCalcClient {
	return &coinCalcClient{cc}
}

func (c *coinCalcClient) GetCoins(ctx context.Context, in *CoinListRequest, opts ...grpc.CallOption) (*CoinListResponse, error) {
	out := new(CoinListResponse)
	err := grpc.Invoke(ctx, "/CoinCalc.CoinCalc/GetCoins", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coinCalcClient) GetCoinPrices(ctx context.Context, in *PriceRequest, opts ...grpc.CallOption) (*CoinPriceResponse, error) {
	out := new(CoinPriceResponse)
	err := grpc.Invoke(ctx, "/CoinCalc.CoinCalc/GetCoinPrices", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coinCalcClient) SetUserCoin(ctx context.Context, in *SetUserCoinRequest, opts ...grpc.CallOption) (*SetUserCoinResponse, error) {
	out := new(SetUserCoinResponse)
	err := grpc.Invoke(ctx, "/CoinCalc.CoinCalc/SetUserCoin", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coinCalcClient) GetUserCoins(ctx context.Context, in *GetUserCoinRequest, opts ...grpc.CallOption) (*GetUserCoinsResponse, error) {
	out := new(GetUserCoinsResponse)
	err := grpc.Invoke(ctx, "/CoinCalc.CoinCalc/GetUserCoins", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coinCalcClient) DeleteUserCoin(ctx context.Context, in *DeleteUserCoinRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/CoinCalc.CoinCalc/DeleteUserCoin", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for CoinCalc service

type CoinCalcServer interface {
	GetCoins(context.Context, *CoinListRequest) (*CoinListResponse, error)
	GetCoinPrices(context.Context, *PriceRequest) (*CoinPriceResponse, error)
	SetUserCoin(context.Context, *SetUserCoinRequest) (*SetUserCoinResponse, error)
	GetUserCoins(context.Context, *GetUserCoinRequest) (*GetUserCoinsResponse, error)
	DeleteUserCoin(context.Context, *DeleteUserCoinRequest) (*Empty, error)
}

func RegisterCoinCalcServer(s *grpc.Server, srv CoinCalcServer) {
	s.RegisterService(&_CoinCalc_serviceDesc, srv)
}

func _CoinCalc_GetCoins_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CoinListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoinCalcServer).GetCoins(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CoinCalc.CoinCalc/GetCoins",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoinCalcServer).GetCoins(ctx, req.(*CoinListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoinCalc_GetCoinPrices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PriceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoinCalcServer).GetCoinPrices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CoinCalc.CoinCalc/GetCoinPrices",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoinCalcServer).GetCoinPrices(ctx, req.(*PriceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoinCalc_SetUserCoin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetUserCoinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoinCalcServer).SetUserCoin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CoinCalc.CoinCalc/SetUserCoin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoinCalcServer).SetUserCoin(ctx, req.(*SetUserCoinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoinCalc_GetUserCoins_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserCoinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoinCalcServer).GetUserCoins(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CoinCalc.CoinCalc/GetUserCoins",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoinCalcServer).GetUserCoins(ctx, req.(*GetUserCoinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoinCalc_DeleteUserCoin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserCoinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoinCalcServer).DeleteUserCoin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CoinCalc.CoinCalc/DeleteUserCoin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoinCalcServer).DeleteUserCoin(ctx, req.(*DeleteUserCoinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CoinCalc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "CoinCalc.CoinCalc",
	HandlerType: (*CoinCalcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCoins",
			Handler:    _CoinCalc_GetCoins_Handler,
		},
		{
			MethodName: "GetCoinPrices",
			Handler:    _CoinCalc_GetCoinPrices_Handler,
		},
		{
			MethodName: "SetUserCoin",
			Handler:    _CoinCalc_SetUserCoin_Handler,
		},
		{
			MethodName: "GetUserCoins",
			Handler:    _CoinCalc_GetUserCoins_Handler,
		},
		{
			MethodName: "DeleteUserCoin",
			Handler:    _CoinCalc_DeleteUserCoin_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "coin_calc.proto",
}

func init() { proto.RegisterFile("coin_calc.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 601 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0xdd, 0x6a, 0xdb, 0x4c,
	0x10, 0xc5, 0xb2, 0x9d, 0xd8, 0x63, 0x7f, 0x76, 0xbe, 0x4d, 0x9a, 0xaa, 0x4a, 0x7f, 0xd2, 0x25,
	0x85, 0x94, 0x42, 0x2e, 0x12, 0x0a, 0x09, 0xf4, 0xa6, 0xb1, 0x4b, 0x4a, 0x09, 0xb4, 0x38, 0xa4,
	0xb9, 0x14, 0xeb, 0xf5, 0x90, 0x08, 0xcb, 0x5a, 0x55, 0xbb, 0x4a, 0xf1, 0x5d, 0x1f, 0xad, 0xaf,
	0xd4, 0x37, 0x28, 0x1a, 0x49, 0x96, 0x5c, 0x2b, 0x10, 0xdf, 0xcd, 0xce, 0x39, 0x67, 0x66, 0x67,
	0xcf, 0xb0, 0xd0, 0x97, 0xca, 0x0b, 0x5c, 0x29, 0x7c, 0x79, 0x14, 0x46, 0xca, 0x28, 0xd6, 0x1a,
	0x28, 0x2f, 0x18, 0x08, 0x5f, 0xf2, 0x37, 0xd0, 0x4f, 0xe2, 0x4b, 0x4f, 0x9b, 0x11, 0xfe, 0x88,
	0x51, 0x1b, 0xc6, 0xa0, 0x11, 0x8a, 0x5b, 0xb4, 0x6b, 0xfb, 0xb5, 0xc3, 0xe6, 0x88, 0x62, 0xfe,
	0xbb, 0x0e, 0x8d, 0x84, 0xc7, 0x7a, 0x60, 0x79, 0x13, 0x82, 0xda, 0x23, 0xcb, 0x9b, 0xb0, 0x5d,
	0xd8, 0xd0, 0xf3, 0xd9, 0x58, 0xf9, 0xb6, 0x45, 0xb9, 0xec, 0x94, 0x14, 0x09, 0xc4, 0x0c, 0xed,
	0x3a, 0x65, 0x29, 0x66, 0x7b, 0xd0, 0x0e, 0x23, 0x4f, 0xa2, 0x1b, 0xeb, 0x89, 0xdd, 0x20, 0xa0,
	0x45, 0x89, 0x6b, 0x3d, 0x29, 0xc0, 0xb1, 0x91, 0x76, 0xb3, 0x04, 0x9e, 0x1b, 0xc9, 0xde, 0xc3,
	0xd3, 0x10, 0x23, 0x89, 0x81, 0x71, 0xe5, 0x9d, 0x08, 0x6e, 0xd1, 0x55, 0x01, 0xba, 0x77, 0x2a,
	0x8e, 0xec, 0x0d, 0xa2, 0xee, 0x64, 0xf0, 0x80, 0xd0, 0xaf, 0x01, 0x7e, 0x56, 0x71, 0xc4, 0x4e,
	0x60, 0xb7, 0x42, 0x36, 0x11, 0x73, 0x7b, 0x93, 0x54, 0xdb, 0xff, 0xaa, 0x86, 0x62, 0xfe, 0x40,
	0xaf, 0x9f, 0x88, 0x53, 0xbb, 0x55, 0xdd, 0xeb, 0x06, 0x71, 0xca, 0x0e, 0xa0, 0x37, 0x13, 0xd1,
	0x14, 0x8d, 0x2b, 0x45, 0x48, 0x13, 0xb6, 0x89, 0xdd, 0x4d, 0xb3, 0x03, 0x11, 0x26, 0x53, 0xbe,
	0x03, 0x96, 0x5d, 0xc1, 0xbd, 0x57, 0x7e, 0x3c, 0x0b, 0x88, 0x09, 0xc4, 0xec, 0x2b, 0xba, 0xc0,
	0x77, 0xca, 0x27, 0xe4, 0xb7, 0xb0, 0x25, 0xee, 0x85, 0xe7, 0x8b, 0xb1, 0x8f, 0xae, 0x8e, 0xc3,
	0xd0, 0x9f, 0xdb, 0x9d, 0x94, 0xba, 0xc8, 0x5f, 0x51, 0x9a, 0xbd, 0x86, 0xae, 0x51, 0x46, 0xf8,
	0x39, 0xad, 0x4b, 0xb4, 0x0e, 0xe5, 0x52, 0x0a, 0xff, 0x55, 0x83, 0xd6, 0xb5, 0xc6, 0x88, 0x6c,
	0x64, 0xd0, 0x88, 0x35, 0x46, 0x99, 0x91, 0x14, 0xaf, 0x65, 0xe5, 0x16, 0xd4, 0x65, 0x60, 0x32,
	0x13, 0x93, 0x90, 0x71, 0x68, 0x24, 0x5b, 0x46, 0xd6, 0x75, 0x8e, 0x7b, 0x47, 0xf9, 0x86, 0x51,
	0x30, 0x22, 0x8c, 0x9f, 0xc2, 0x56, 0xb1, 0x6c, 0x3a, 0x54, 0x81, 0x46, 0x76, 0x00, 0xcd, 0x04,
	0xd3, 0x76, 0x6d, 0xbf, 0x5e, 0x21, 0x4c, 0x41, 0x7e, 0x08, 0xdd, 0x6f, 0xc9, 0x32, 0xe4, 0x3b,
	0x6a, 0xc3, 0x66, 0x7a, 0xbb, 0x54, 0xd7, 0x1e, 0xe5, 0x47, 0x7e, 0x06, 0xff, 0x27, 0xc2, 0x8c,
	0xbd, 0x56, 0x93, 0x53, 0x60, 0x57, 0x68, 0xf2, 0x37, 0xca, 0x5b, 0x71, 0xb0, 0x62, 0x49, 0x0f,
	0xd5, 0x39, 0x66, 0x85, 0x70, 0x41, 0xb3, 0x62, 0xc9, 0xcf, 0x60, 0x7b, 0x49, 0x99, 0xb5, 0x7d,
	0x8c, 0xf4, 0x10, 0xd8, 0xc5, 0x6a, 0xd3, 0x0a, 0x7f, 0xf8, 0x07, 0xd8, 0x29, 0x31, 0x75, 0x69,
	0xb8, 0x7a, 0x2c, 0xf3, 0xd1, 0xaa, 0xda, 0x24, 0x30, 0xbf, 0x81, 0x27, 0x43, 0xf4, 0xd1, 0xe0,
	0x23, 0x5a, 0xad, 0xb3, 0x0a, 0x7c, 0x13, 0x9a, 0x9f, 0x66, 0xa1, 0x99, 0x1f, 0xff, 0xb1, 0x60,
	0xf1, 0xaf, 0xb0, 0x8f, 0xd0, 0xba, 0x40, 0x43, 0x17, 0x65, 0xcf, 0x96, 0x9f, 0xbb, 0xf4, 0xd7,
	0x38, 0x4e, 0x15, 0x94, 0xcd, 0x35, 0x84, 0xff, 0xb2, 0x12, 0x64, 0xa6, 0x66, 0xbb, 0x05, 0xb9,
	0xbc, 0x0c, 0xce, 0xde, 0x72, 0x91, 0x65, 0xeb, 0xbf, 0x40, 0xa7, 0x64, 0x0d, 0x7b, 0x5e, 0x70,
	0x57, 0xbd, 0x76, 0x5e, 0x3c, 0x80, 0x66, 0xb5, 0x2e, 0xa1, 0x5b, 0x76, 0xa0, 0x5c, 0x6c, 0xd5,
	0x43, 0xe7, 0x65, 0x25, 0x5a, 0xf8, 0x76, 0x0e, 0xbd, 0x65, 0x47, 0xd8, 0xab, 0x42, 0x51, 0xe9,
	0x95, 0xd3, 0x2f, 0x08, 0xf4, 0xe6, 0xe3, 0x0d, 0xfa, 0xcf, 0x4f, 0xfe, 0x06, 0x00, 0x00, 0xff,
	0xff, 0xd8, 0xee, 0x28, 0x93, 0xe2, 0x05, 0x00, 0x00,
}
