// DO NOT EDIT.
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: proto/coin_calc.proto
//
// For information on using the generated types, please see the documenation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that your are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

struct CoinCalc_CoinListRequest: SwiftProtobuf.Message {
  static let protoMessageName: String = _protobuf_package + ".CoinListRequest"

  var page: Int32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  /// Used by the decoding initializers in the SwiftProtobuf library, not generally
  /// used directly. `init(serializedData:)`, `init(jsonUTF8Data:)`, and other decoding
  /// initializers are defined in the SwiftProtobuf library. See the Message and
  /// Message+*Additions` files.
  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularInt32Field(value: &self.page)
      default: break
      }
    }
  }

  /// Used by the encoding methods of the SwiftProtobuf library, not generally
  /// used directly. `Message.serializedData()`, `Message.jsonUTF8Data()`, and
  /// other serializer methods are defined in the SwiftProtobuf library. See the
  /// `Message` and `Message+*Additions` files.
  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.page != 0 {
      try visitor.visitSingularInt32Field(value: self.page, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }
}

struct CoinCalc_Coin: SwiftProtobuf.Message {
  static let protoMessageName: String = _protobuf_package + ".Coin"

  var id: String = String()

  var symbol: String = String()

  var name: String = String()

  var priceUsd: String = String()

  var priceBtc: String = String()

  var percentChangeOneHour: String = String()

  var percentChangeOneDay: String = String()

  var percentChangeOneWeek: String = String()

  var marketCapUsd: String = String()

  var oneDayVolumnUsd: String = String()

  var availableSupply: String = String()

  var totalSupply: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  /// Used by the decoding initializers in the SwiftProtobuf library, not generally
  /// used directly. `init(serializedData:)`, `init(jsonUTF8Data:)`, and other decoding
  /// initializers are defined in the SwiftProtobuf library. See the Message and
  /// Message+*Additions` files.
  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularStringField(value: &self.id)
      case 2: try decoder.decodeSingularStringField(value: &self.symbol)
      case 3: try decoder.decodeSingularStringField(value: &self.name)
      case 4: try decoder.decodeSingularStringField(value: &self.priceUsd)
      case 5: try decoder.decodeSingularStringField(value: &self.priceBtc)
      case 6: try decoder.decodeSingularStringField(value: &self.percentChangeOneHour)
      case 7: try decoder.decodeSingularStringField(value: &self.percentChangeOneDay)
      case 8: try decoder.decodeSingularStringField(value: &self.percentChangeOneWeek)
      case 9: try decoder.decodeSingularStringField(value: &self.marketCapUsd)
      case 10: try decoder.decodeSingularStringField(value: &self.oneDayVolumnUsd)
      case 11: try decoder.decodeSingularStringField(value: &self.availableSupply)
      case 12: try decoder.decodeSingularStringField(value: &self.totalSupply)
      default: break
      }
    }
  }

  /// Used by the encoding methods of the SwiftProtobuf library, not generally
  /// used directly. `Message.serializedData()`, `Message.jsonUTF8Data()`, and
  /// other serializer methods are defined in the SwiftProtobuf library. See the
  /// `Message` and `Message+*Additions` files.
  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.id.isEmpty {
      try visitor.visitSingularStringField(value: self.id, fieldNumber: 1)
    }
    if !self.symbol.isEmpty {
      try visitor.visitSingularStringField(value: self.symbol, fieldNumber: 2)
    }
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 3)
    }
    if !self.priceUsd.isEmpty {
      try visitor.visitSingularStringField(value: self.priceUsd, fieldNumber: 4)
    }
    if !self.priceBtc.isEmpty {
      try visitor.visitSingularStringField(value: self.priceBtc, fieldNumber: 5)
    }
    if !self.percentChangeOneHour.isEmpty {
      try visitor.visitSingularStringField(value: self.percentChangeOneHour, fieldNumber: 6)
    }
    if !self.percentChangeOneDay.isEmpty {
      try visitor.visitSingularStringField(value: self.percentChangeOneDay, fieldNumber: 7)
    }
    if !self.percentChangeOneWeek.isEmpty {
      try visitor.visitSingularStringField(value: self.percentChangeOneWeek, fieldNumber: 8)
    }
    if !self.marketCapUsd.isEmpty {
      try visitor.visitSingularStringField(value: self.marketCapUsd, fieldNumber: 9)
    }
    if !self.oneDayVolumnUsd.isEmpty {
      try visitor.visitSingularStringField(value: self.oneDayVolumnUsd, fieldNumber: 10)
    }
    if !self.availableSupply.isEmpty {
      try visitor.visitSingularStringField(value: self.availableSupply, fieldNumber: 11)
    }
    if !self.totalSupply.isEmpty {
      try visitor.visitSingularStringField(value: self.totalSupply, fieldNumber: 12)
    }
    try unknownFields.traverse(visitor: &visitor)
  }
}

struct CoinCalc_CoinListResponse: SwiftProtobuf.Message {
  static let protoMessageName: String = _protobuf_package + ".CoinListResponse"

  var coins: [CoinCalc_Coin] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  /// Used by the decoding initializers in the SwiftProtobuf library, not generally
  /// used directly. `init(serializedData:)`, `init(jsonUTF8Data:)`, and other decoding
  /// initializers are defined in the SwiftProtobuf library. See the Message and
  /// Message+*Additions` files.
  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeRepeatedMessageField(value: &self.coins)
      default: break
      }
    }
  }

  /// Used by the encoding methods of the SwiftProtobuf library, not generally
  /// used directly. `Message.serializedData()`, `Message.jsonUTF8Data()`, and
  /// other serializer methods are defined in the SwiftProtobuf library. See the
  /// `Message` and `Message+*Additions` files.
  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.coins.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.coins, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }
}

struct CoinCalc_PriceRequest: SwiftProtobuf.Message {
  static let protoMessageName: String = _protobuf_package + ".PriceRequest"

  var coinids: [String] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  /// Used by the decoding initializers in the SwiftProtobuf library, not generally
  /// used directly. `init(serializedData:)`, `init(jsonUTF8Data:)`, and other decoding
  /// initializers are defined in the SwiftProtobuf library. See the Message and
  /// Message+*Additions` files.
  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeRepeatedStringField(value: &self.coinids)
      default: break
      }
    }
  }

  /// Used by the encoding methods of the SwiftProtobuf library, not generally
  /// used directly. `Message.serializedData()`, `Message.jsonUTF8Data()`, and
  /// other serializer methods are defined in the SwiftProtobuf library. See the
  /// `Message` and `Message+*Additions` files.
  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.coinids.isEmpty {
      try visitor.visitRepeatedStringField(value: self.coinids, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }
}

struct CoinCalc_CoinPriceResponse: SwiftProtobuf.Message {
  static let protoMessageName: String = _protobuf_package + ".CoinPriceResponse"

  var coins: [CoinCalc_Coin] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  /// Used by the decoding initializers in the SwiftProtobuf library, not generally
  /// used directly. `init(serializedData:)`, `init(jsonUTF8Data:)`, and other decoding
  /// initializers are defined in the SwiftProtobuf library. See the Message and
  /// Message+*Additions` files.
  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeRepeatedMessageField(value: &self.coins)
      default: break
      }
    }
  }

  /// Used by the encoding methods of the SwiftProtobuf library, not generally
  /// used directly. `Message.serializedData()`, `Message.jsonUTF8Data()`, and
  /// other serializer methods are defined in the SwiftProtobuf library. See the
  /// `Message` and `Message+*Additions` files.
  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.coins.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.coins, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "CoinCalc"

extension CoinCalc_CoinListRequest: SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "page"),
  ]

  func _protobuf_generated_isEqualTo(other: CoinCalc_CoinListRequest) -> Bool {
    if self.page != other.page {return false}
    if unknownFields != other.unknownFields {return false}
    return true
  }
}

extension CoinCalc_Coin: SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "id"),
    2: .same(proto: "symbol"),
    3: .same(proto: "name"),
    4: .standard(proto: "price_usd"),
    5: .standard(proto: "price_btc"),
    6: .standard(proto: "percent_change_one_hour"),
    7: .standard(proto: "percent_change_one_day"),
    8: .standard(proto: "percent_change_one_week"),
    9: .standard(proto: "market_cap_usd"),
    10: .standard(proto: "one_day_volumn_usd"),
    11: .standard(proto: "available_supply"),
    12: .standard(proto: "total_supply"),
  ]

  func _protobuf_generated_isEqualTo(other: CoinCalc_Coin) -> Bool {
    if self.id != other.id {return false}
    if self.symbol != other.symbol {return false}
    if self.name != other.name {return false}
    if self.priceUsd != other.priceUsd {return false}
    if self.priceBtc != other.priceBtc {return false}
    if self.percentChangeOneHour != other.percentChangeOneHour {return false}
    if self.percentChangeOneDay != other.percentChangeOneDay {return false}
    if self.percentChangeOneWeek != other.percentChangeOneWeek {return false}
    if self.marketCapUsd != other.marketCapUsd {return false}
    if self.oneDayVolumnUsd != other.oneDayVolumnUsd {return false}
    if self.availableSupply != other.availableSupply {return false}
    if self.totalSupply != other.totalSupply {return false}
    if unknownFields != other.unknownFields {return false}
    return true
  }
}

extension CoinCalc_CoinListResponse: SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "coins"),
  ]

  func _protobuf_generated_isEqualTo(other: CoinCalc_CoinListResponse) -> Bool {
    if self.coins != other.coins {return false}
    if unknownFields != other.unknownFields {return false}
    return true
  }
}

extension CoinCalc_PriceRequest: SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "coinids"),
  ]

  func _protobuf_generated_isEqualTo(other: CoinCalc_PriceRequest) -> Bool {
    if self.coinids != other.coinids {return false}
    if unknownFields != other.unknownFields {return false}
    return true
  }
}

extension CoinCalc_CoinPriceResponse: SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "coins"),
  ]

  func _protobuf_generated_isEqualTo(other: CoinCalc_CoinPriceResponse) -> Bool {
    if self.coins != other.coins {return false}
    if unknownFields != other.unknownFields {return false}
    return true
  }
}
